### ISSUE TITLE
Panic when using it in Leptos SSR mode

### ISSUE THREAD

**Issue by bochaco** [clementwanjau/apexcharts-rs#5]
I'm trying to use this crate with Leptos SSR mode but it's crashing with the following error (just trying out the example code from README):
```
thread 'main' panicked at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.93/src/lib.rs:1021:1:
function not implemented on non-wasm32 targets
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: wasm_bindgen::__wbindgen_string_new
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.93/src/lib.rs:46:17
   3: wasm_bindgen::JsValue::from_str
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.93/src/lib.rs:133:32
   4: apexcharts_rs::leptos::__ApexChartComponent
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/apexcharts-rs-0.1.6/src/leptos.rs:126:30
   5: apexcharts_rs::leptos::ApexChartComponent::{{closure}}
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/apexcharts-rs-0.1.6/src/leptos.rs:50:1
   6: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.14/src/components.rs:281:49
   7: leptos_reactive::runtime::RuntimeId::untrack::{{closure}}
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.6.14/src/runtime.rs:953:32
   8: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/bochaco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.6.14/src/runtime.rs:700:41
...



thread 'main' panicked at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:260:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
fatal runtime error: thread local panicked on drop
```

**Comment by clementwanjau** [comment]
Thank you for raising this issue. I'll look into it and fix this ASAP.

Cheers

**Comment by Creative-Difficulty** [comment]
@clementwanjau is this fixed?

**Comment by clementwanjau** [comment]
This has been fixed in the latest release.

**Comment by bochaco** [comment]
Thanks @clementwanjau !
